<?php

/**
 * Copyright since 2007 PrestaShop SA and Contributors
 * PrestaShop is an International Registered Trademark & Property of PrestaShop SA
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/OSL-3.0
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@prestashop.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade PrestaShop to newer
 * versions in the future. If you wish to customize PrestaShop for your
 * needs please refer to https://devdocs.prestashop.com/ for more information.
 *
 * @author    PrestaShop SA and Contributors <contact@prestashop.com>
 * @copyright Since 2007 PrestaShop SA and Contributors
 * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
 */

class miraklconnector extends Module{
    public function __construct($name = null, Context $context = null)
    {
        $this->name = "miraklconnector";
        $this->tab = "front_office_features";
        $this->version = "0.0.1";
        $this->author = "Johannes Thyroff";
        $this->need_instance = 0;
        $this->ps_versions_compliancy = [
            "min" => "1.5",
            "max" => _PS_VERSION_
        ];
        $this->bootstrap = true;
        parent::__construct();

        $this->displayName = $this->l("Mirakl Connector");
        $this->description = $this->l("Prestashop module to integrate Mirakl orders in Prestashop using the Mirakl sdk.");
        $this->confirmUninstall = $this->l("Don't delete this module :(");
    }

    public function getContent(){
        //this is the configuration page
        return $this->display(__FILE__, 'views/templates/admin/configuration.tpl');
    }

    public function install()
    {
        return parent::install(); // TODO: Change the autogenerated stub
    }

    public function uninstall()
    {
        return parent::uninstall(); // TODO: Change the autogenerated stub
    }
}