# @see https://devdocs.prestashop.com/1.7/modules/concepts/controllers/admin-controllers/#how-to-map-an-action-of-your-controller-to-a-uri
ps_controller_mirakl_sell_manual_tab:
    path: /mirakl-sell-manual-tab
    methods: [GET]
    defaults:
        _controller: 'Module\MiraklConnector\Controller\Admin\MiraklSellManualTabController::indexAction'

mirakl_connector_index:
    path: /demo-grid
    methods: [GET]
    defaults:
        _controller: 'Module\MiraklConnector\Controller\Admin\IndexController::indexAction'
        _legacy_controller: 'AdminDemoGrid'
        _legacy_link: 'AdminDemoGrid'

mirakl_connector_search:
    path: /demo-grid
    methods: [POST]
    defaults:
        _controller: 'Module\MiraklConnector\Controller\Admin\IndexController::searchAction'
        _legacy_controller: 'AdminDemoGrid'
        _legacy_link: 'AdminDemoGrid:search'
