services:
  # Grid services
  mirakl_connector.grid.definition.factory.products:
    class: 'Module\MiraklConnector\Grid\Definition\Factory\ProductGridDefinitionFactory'
    parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'

  mirakl_connector.grid.query_builder.product:
    class: 'Module\MiraklConnector\Grid\Query\ProductQueryBuilder'
    public: true
    arguments:
      - '@doctrine.dbal.custom_connection'  # Correct the order of the arguments
      - ''
      - '@prestashop.core.query.doctrine_search_criteria_applicator'  # Correct the service name
      - "@=service('prestashop.adapter.legacy.context').getContext().language.id"
      - "@=service('prestashop.adapter.legacy.context').getContext().shop.id"
      - "@=service('prestashop.adapter.legacy.context').getContext().shop.id_shop_group"
      - "@=service('prestashop.adapter.legacy.context').getContext().shop.getGroup().share_stock"
      - '@prestashop.core.grid.query.filter.doctrine_filter_applicator'
      - '@prestashop.adapter.legacy.configuration'



  doctrine.dbal.custom_connection:
    class: Doctrine\DBAL\Connection
    public: true
    factory: ['Doctrine\DBAL\DriverManager', 'getConnection']
    arguments:
      -
        dbname: 'PC_CompOrders'
        user: 'root'
        password: 'mycustompassword'
        host: '172.18.0.2'
        driver: 'pdo_mysql'


  mirakl_connector.grid.data_provider.products:
    class: 'Module\MiraklConnector\Grid\Data\Factory\ProductGridDataFactory'
    arguments:
      - '@mirakl_connector.grid.query_builder.product'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.core.grid.query.doctrine_query_parser'
      - 'product'

  mirakl_connector.grid.factory.products:
    class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
    public: true
    arguments:
      - '@mirakl_connector.grid.definition.factory.products'
      - '@mirakl_connector.grid.data_provider.products'
      - '@prestashop.core.grid.filter.form_factory'
      - '@prestashop.core.hook.dispatcher'
